### PR TITLE
Fix create and queue not working with 1 param in IPC mode

### LINKED ISSUE #184: [bug] ipc mode `q -w 12` not work.
## Description

Expected: create a notification with 12 minutes work and 5 minutes break.

image

Let's fix it.

### PR DESCRIPTION
**Pull request by TheRustyPickle**
Previously on IPC mode when parsing break and work time, it would return an error if either was absent. Now modified to use the default value for the missing parameter. Resolves #184

### CODE REVIEW

**Comment by 24seconds** [comment]
Hello, @TheRustyPickle ! How's it going? I saw you are working on rex 👍👍👍. Thank you for the contribution again! 

Aha.. at that time, to not to make a discrepancy between `ipc mode` and  `standalone mode`, I tried to use shared function. `parse_work_and_break_time` is the one of my intention. But currently it's not shared.
So.. How about modify this function so that it can be shared in here https://github.com/24seconds/rust-cli-pomodoro/blob/a674ec885b37881091e984ae4db43c7869311049/src/notification/mod.rs#L264-L282?

**Comment by 24seconds** [comment]
Thank you for the quick action @TheRustyPickle . 
I think we need to think about `configuration`. 

When you think about `ipc` mode, there are two components. The `rust-cli-pomodoro` app which is acting as `ipc` server and the `rust-cli-pomodoro` app which is acting as `ipc` client.  
Configuration is usually used when the `rust-cli-pomodoro` app starts up as standalone mode or `ipc` server. https://github.com/24seconds/rust-cli-pomodoro/blob/a674ec885b37881091e984ae4db43c7869311049/src/main.rs#L176-L192

Therefore, I think considering configuration in `ipc` client is not proper.  

[Suggestion]
The proper behavior of `q -w 12` in `ipc` mode would look like below.
- `rust-cli-pomodoro` app is running with some configuration. Let say `break_time_default_value` is 10.
- Typed `pomodoro q -w 12` in another terminal tab. There is no configuration related command here.
- Running `rust-cli-pomodoro` app should handle this without problem and creates a notification with 12 minutes work and `10 minutes` break. Note that configuration is used in running `rust-cli-pomodoro`.

To do this, maybe `parse_work_and_break_time` function should take `Option` of `Arc<Configuration`? (I don't know exactly. Fill free to modify the function so that `rust-cli-pomodoro` works properly as I described)

What do you think about this? Could you take a look?

**Comment by TheRustyPickle** [comment]
Thanks for your input, @24seconds. Please correct me if I misunderstood, the configuration should only be used in the `standalone` mode. In `IPC` mode, it should ignore any configuration and use `DEFAULT_WORK_TIME` and `DEFAULT_BREAK_TIME` accordingly for missing the parameter if any.

**Comment by 24seconds** [comment]
> Thanks for your input, @24seconds. Please correct me if I misunderstood, the configuration should only be used in the `standalone` mode. In `IPC` mode, it should ignore any configuration and use `DEFAULT_WORK_TIME` and `DEFAULT_BREAK_TIME` accordingly for missing the parameter if any.

Ah, this is quite tricky part. I should revisit this later.
Actually `ipc` server mode is `standalone` mode. The first `rust-cli-pomodoro` app started works as `standalone` mode. And it can serve `ipc` client request.  If you start `rust-cli-pomodoro` app in another terminal tab, then that would just work as standalone mode.  

Let say we started `pomodoro 1`, `pomodoro 2` and `pomodoro 3` as standalone mode. Then the early created `pomodoro 1` app would work as `ipc` server mode.  
When you typed `pomodoro q -w 12` in another terminal tab, then `pomodoro 1` is in charge of handling the request.  
Therefore, `pomodoro 1`'s configuration should be considered when handling the `q -w 12` ipc request.

Run the app and try some commands, you will understand @TheRustyPickle

**Comment by TheRustyPickle** [comment]
Thanks for the explanation. I tried the app already, I misunderstood some of the terms 🙏. I got what you mean now. Will work on fixing this.

**Comment by 24seconds** [comment]
I guess maybe you are not the only one who misunderstands the term. Let me follow up clarifying the terms. 🙇

**Comment by TheRustyPickle** [comment]
Hello again, @24seconds, the latest commit should fix the issues we talked about earlier. Do take a look when you are available and let me know what you think🙏

**Review by 24seconds — APPROVED** [review]
LGTM! Thank you for the contribution!

**Pull request merged**
